version: '3.8'

services:
  hugo-site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcmurray-tech
    restart: unless-stopped
    networks:
      - proxynet

networks:
  proxynet:
    external: true
